name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o frate-${{ matrix.goos }}-${{ matrix.goarch }} .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frate-${{ matrix.goos }}-${{ matrix.goarch }}
        path: frate-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
    - uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: frate-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}-${{ github.run_id }}"
        release_name: "Release ${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: frate-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_name: frate-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_content_type: application/octet-stream

